### PR TITLE
Connection lost during socket_recv

### LINKED ISSUE #29: mbed-os TCP test failure : TCPSOCKET_ENDPOINT_CLOSE test case
### Status
TCP test is FAIL for both DISCO F413 and L475 :

| target               | platform_name | test suite                                                                   | test case                                                                                         | passed | failed | result  | elapsed_time (sec) |
|----------------------|---------------|------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|--------|--------|---------|--------------------|
| DISCO_F413ZH-ARM     | DISCO_F413ZH  | tests-netsocket-tcp                                                          | TCPSOCKET_ENDPOINT_CLOSE                                                                          | 0      | 1      | FAIL    | 0.64               |

### Console log:

[1536618580.93][CONN][RXD] >>> Running case #14: 'TCPSOCKET_ENDPOINT_CLOSE'...
[1536618580.98][CONN][INF] found KV pair in stream: {{__testcase_start;TCPSOCKET_ENDPOINT_CLOSE}}, queued...
[1536618581.56][CONN][RXD] :75::FAIL

### Information from Seppo:

https://tools.ietf.org/html/rfc867
"The service closes the connection after sending the quote."

So yes, it is supposed to close.

From API point of view, we try to follow POSIX as close as possible.
In POSIX: recv() http://pubs.opengroup.org/onlinepubs/9699919799/functions/recv.html
"Upon successful completion, recv() shall return the length of the message in bytes. If no messages are available to be received and the peer has performed an orderly shutdown, recv() shall return 0. Otherwise, -1 shall be returned and errno set to indicate the error."

In Mbed OS TCPSocket::recv(): https://os.mbed.com/docs/v5.9/mbed-os-api-doxy/class_t_c_p_socket.html#ac5f7d7ea02ce27bde53f6c7da0b2b75a
"Returns: Number of received bytes on success, negative error code on failure. If no data is available to be received and the peer has performed an orderly shutdown, recv() returns 0."

So you need to return zero, at least for first recv() call, because closing a TCP socket it considered normal operation, so you cannot throw an error there.

Also, note that it has to be proper connection closing.. RESET flag, or lost connection are allowed to return error, but cleanly shutdown should be OK(0) for the first recv() call.

### PR DESCRIPTION
**Pull request by jeromecoutant**
This fixes #29 

In  TCPSocket::recv() we need to return zero because closing a TCP socket it considered normal operation.
Details in #29 

@SeppoTakalo @screamerbg

### CODE REVIEW

File: ISM43362Interface.cpp [hunk 1]
```diff
@@ -434,7 +434,7 @@ int ISM43362Interface::socket_recv(void *handle, void *data, unsigned size)
 
     if (!socket->connected) {
         _mutex.unlock();
-        return NSAPI_ERROR_CONNECTION_LOST;
+        return 0;
```
Comment (LMESTM) [inline ISM43362Interface.cpp]: if we end up here, I agree this is most probably an "orderly" connection closed ...

File: ISM43362Interface.cpp [hunk 2]
```diff
@@ -446,7 +446,7 @@ int ISM43362Interface::socket_recv(void *handle, void *data, unsigned size)
             socket->connected = false;
             debug_if(_ism_debug, "ISM43362Interface socket_recv: socket closed\r\n");
             _mutex.unlock();
-            return NSAPI_ERROR_CONNECTION_LOST;
+            return 0;
```
Comment (LMESTM) [inline ISM43362Interface.cpp]: but here, this sounds more like a network loss. 
Have you checked in #29 if only the previous return is enough to solve the issue ?

**Comment by jeromecoutant** [comment]
Code updated

| target                  | platform_name       | test suite          | test case                            | passed | failed | result | elapsed_time (sec) |
|-------------------------|---------------------|---------------------|--------------------------------------|--------|--------|--------|--------------------|
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | tests-netsocket-tcp | TCPSOCKET_ENDPOINT_CLOSE             | 1      | 0      | OK     | 1.31               |

**Comment by SeppoTakalo** [comment]
I don't agree with the first comment that @LMESTM gave.
Now the driver is returning zero, only if background receiver thread notices that socket is closed.

In both cases the driver is calling `_ism.check_recv_status()` either directly from `socket_recv()` or from the background receiver thread `socket_check_read()`

So which one gets first, is just a timing.

I'm not sure if ISM43362 is capable of telling the difference of network failures, connection reset or orderly shutdown. If not, I recommend returning zero every time you notice that stream is closed and `recv()` is called.

Of course, if you can tell the difference, then it is OK to return error codes.

I did a quick look at the driver and seems to not do the same check when sending the data.
If somebody tries to send data to closed socket, you can immediately return `NSAPI_ERROR_CONNECTION_LOST`

Other than those, this change looks OK. I'm just worrying about the timing.. it might be that you fixed it only 90% of the time.

**Comment by LMESTM** [comment]
@SeppoTakalo 
Ok I get your point - that's valid. 
the thing we can get a proper notification from the device when the connection was either lost or close from the remote side. So ok to move back to initial proposal from Jérôme.
