### PR TITLE
Network status API implementation

### LINKED ISSUE #31: mbed-os interface tests failed
Hi

tests-network-interface is OK with all Ethernet boards,
but failed with Wifi boards :

Target | Toolchain | TestSuite | TestCase | mbed-os-5.10.1
-- | -- | -- | -- | --
DISCO_F413ZH | ARM | tests-network-interface | NETWORKINTERFACE_STATUS | ERROR
DISCO_F413ZH | GCC_ARM | tests-network-interface | NETWORKINTERFACE_STATUS | ERROR
DISCO_F413ZH | IAR | tests-network-interface | NETWORKINTERFACE_STATUS | ERROR
DISCO_L475VG_IOT01A | ARM | tests-network-interface | NETWORKINTERFACE_STATUS | ERROR
DISCO_L475VG_IOT01A | GCC_ARM | tests-network-interface | NETWORKINTERFACE_STATUS | ERROR
DISCO_L475VG_IOT01A | IAR | tests-network-interface | NETWORKINTERFACE_STATUS | ERROR

Check

https://github.com/ARMmbed/mbed-os-5-docs/blob/101a69d2c4261e7fd0b15cfaee90b5ce8a944feb/docs/api/networkinterfaces/networkinterface.md

https://github.com/ARMmbed/mbed-os-5-docs/blob/101a69d2c4261e7fd0b15cfaee90b5ce8a944feb/docs/api/networkinterfaces/NetworkStatus.md

@SeppoTakalo

### PR DESCRIPTION
**Pull request by jeromecoutant**
This fixes #31 

https://os.mbed.com/docs/mbed-os/v5.11/apis/network-status.html

| target                  | platform_name       | test suite              | test case                          | passed | failed | result | elapsed_time (sec) |
|-------------------------|---------------------|-------------------------|------------------------------------|--------|--------|--------|--------------------|
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | tests-network-interface | NETWORKINTERFACE_CONN_DISC_REPEAT  | 1      | 0      | OK     | 18.45              |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | tests-network-interface | NETWORKINTERFACE_STATUS            | 1      | 0      | OK     | 19.11              |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | tests-network-interface | NETWORKINTERFACE_STATUS_GET        | 1      | 0      | OK     | 18.44              |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | tests-network-interface | NETWORKINTERFACE_STATUS_NONBLOCK   | 1      | 0      | OK     | 18.52              |

@SeppoTakalo @screamerbg

### CODE REVIEW

**Comment by jeromecoutant** [comment]
> Maybe just need to cover more cases where connection is lost ... (e.g. during call to receive)

I think it's OK with this current implementation:
This interface informs you about connection state, not socket state.

File: ISM43362/ISM43362.cpp [hunk 1]
```diff
@@ -218,13 +218,19 @@ int ISM43362::connect(const char *ap, const char *passPhrase, ism_security_t ap_
...
             if (strstr(tmp, "OK")) {
                 _parser.flush();
+                _conn_status = NSAPI_STATUS_GLOBAL_UP;
+                _conn_stat_cb();
                 return NSAPI_ERROR_OK;
             }
             if (strstr(tmp, "JOIN")) {
                 if (strstr(tmp, "Failed")) {
                     _parser.flush();
+                    _conn_status = NSAPI_STATUS_DISCONNECTED;
```
Comment (SeppoTakalo) [inline ISM43362/ISM43362.cpp]: It should be `CONNECTING` as documented here: https://os.mbed.com/docs/mbed-os/v5.11/apis/network-interfaces.html (scroll down for the state diagram)

**Comment by SeppoTakalo** [comment]
Does the device do reconnection automatically or should you also add handling for that?

File: ISM43362/ISM43362.cpp (hunk 1 above)
Comment (jeromecoutant) [reply ISM43362/ISM43362.cpp]: > It should be CONNECTING

Done
