### PR TITLE
Use the default gethostbyname implementation

### LINKED ISSUE #41: Corrupt address returned in an mbed-os DNS greentea test suite
When running the tests-netsocket-dns test suite I came across a repeatable failure in ASYNCHRONOUS_DNS_NON_ASYNC_AND_ASYNC:
```
[1553519786.14][CONN][RXD] >>> Running case #5: 'ASYNCHRONOUS_DNS_NON_ASYNC_AND_ASYNC'...
[1553519786.15][CONN][INF] found KV pair in stream: {{__testcase_start;ASYNCHRONOUS_DNS_NON_ASYNC_AND_ASYNC}}, queued...
[1553519786.17][CONN][RXD] DNS: query "google.com" => "172.217.16.46"
[1553519786.43][CONN][WRN] UnicodeDecodeError encountered!
[1553519786.43][CONN][RXD] DNS: query "youtube.com" => ":"
mbedgt: :43::FAIL: Expected 0 Was -3009
[1553519786.43][CONN][RXD] :43::FAIL: Expected 0 Was -3009
mbedgt: :44::FAIL: Expression Evaluated To FALSE
[1553519786.43][CONN][RXD] :44::FAIL: Expression Evaluated To FALSE
[1553519786.65][CONN][WRN] UnicodeDecodeError encountered!
[1553519786.65][CONN][RXD] DNS: query "facebook.com" => ":"
mbedgt: :43::FAIL: Expected 0 Was -3009
[1553519786.67][CONN][RXD] :43::FAIL: Expected 0 Was -3009
mbedgt: :44::FAIL: Expression Evaluated To FALSE
[1553519786.67][CONN][RXD] :44::FAIL: Expression Evaluated To FALSE
[1553519786.86][CONN][RXD] DNS: query "wikipedia.org" => "91.198.174.192"
```
Finding the ":" indicates that an IPv6 address has been returned from DNS, rather than IPv4. I have checked that mbed-os is passing an IPv4 version of the address when calling sendto. 
I can only see this failure for DISCO_L475VG_IOT01A and DISCO_F413ZH which are the two boards using the ISM43362 driver. All other boards are passing fine.

Step to reproduce:
1) Compile mbed-os tests (compiler doesn't matter, IAR is just an example)
```
mbed test --compile -t IAR -m DISCO_L475VG_IOT01A -n tests-netsocket-dns --app-config=mbed_app.wlan0.json -v
```
2) Run the compiler test suite:
```
mbed test --run -t IAR -m DISCO_L475VG_IOT01A -n tests-netsocket-dns -v
```

mbed-os was compiled to use Wi-Fi, LWIP and IPv4:
```
 "target_overrides": {
        "*": {
            "target.network-default-interface-type": "WIFI",
            "nsapi.default-stack": "LWIP",
            "lwip.ipv4-enabled": true,
            "lwip.ipv6-enabled": false,
        },
        "DISCO_L475VG_IOT01A": {
            "ism43362.provide-default": true
        }

```

### PR DESCRIPTION
**Pull request by jeromecoutant**
Code is removes as they were no more called any way...

NB: this doesn't fix #41 

@michalpasztamobica
@SeppoTakalo 
@LMESTM

### CODE REVIEW

File: ISM43362Interface.h [hunk 1]
```diff
@@ -135,29 +121,6 @@ class ISM43362Interface : public NetworkStack, public WiFiInterface
...
-     *  If no stack-specific DNS resolution is provided, the hostname
-     *  will be resolve using a UDP socket on the stack.
-     *
-     *  @param address  Destination for the host SocketAddress
-     *  @param host     Hostname to resolve
-     *  @param version  IP version of address to resolve, NSAPI_UNSPEC indicates
-     *                  version is chosen by the stack (defaults to NSAPI_UNSPEC)
-     *  @return         0 on success, negative error code on failure
-     */
-    using NetworkInterface::gethostbyname;
```
Comment (michalpasztamobica) [inline ISM43362Interface.h]: Both the NetworkStack and NetworkInterface provide their implementations of gethostbyname...
If you remove the explicit declaration of which one you want to use, will this code still compile? And if so, which implementation is going to be used?
One way out would be to prepend each call to gethostbyname with an explicit BaseClass:: specifier... Is this the plan?

**Comment by jeromecoutant** [comment]
Verified with mbed-os tests with DISCo F413 and L475 with all tool chains
