### PR TITLE
Wifi scan AP one by one with ATcommand F0=2 available since firmware version 3.5.2.5

### LINKED ISSUE #68: Scan fails when more than about 20 networks are in range
This is a follow-up of an investigation performed in https://github.com/ARMmbed/mbed-os-example-wifi/issues/177.

Quoting @LMESTM 's proposal:

> Driver would need to be modified to:
> 
> * check if firmware version is the latest one
> * select the AT command accordingly (F0=2 if latest firmware version or newer, F0 if older version)
> * list the access points with one of the 2 above methods.

### PR DESCRIPTION
**Pull request by ABOSTM**
Wifi scan AP one by one with ATcommand F0=2 available since firmware version 3.5.2.5

Fixes #68

### CODE REVIEW

**Comment by ABOSTM** [comment]
Hi @junyoun-kim  and @korjaa,
I implement the use of AT command F0=2, to get AP one by one, like suggested in 
https://github.com/ARMmbed/mbed-os-example-wifi/issues/177
Of course the patch is working on my side.
But even if I succeeded to get an environment with 22 AP, I never reproduce the issue. So I am not sure issue is fixed.

So would you be so kind to test my PullRequest and tell me whether it solves the issue ?
Ideally I would suggest to check that issue is still present first before applying the patch, as issue depends on the environment.

**Comment by junyoun-kim** [comment]
@ABOSTM It looks works fine for me!!

File: ISM43362/ISM43362.cpp [hunk 1]
```diff
@@ -435,20 +438,54 @@ int ISM43362::scan(WiFiAccessPoint *res, unsigned limit)
     char *ptr;
     char tmp[256];
     bool found = false;
-
-    if (!(_parser.send("F0"))) {
-        debug_if(_ism_debug, "\tISM43362: scan error\r\n");
-        return 0;
+    bool AP_Scan_1by1 = false;
+
+    /* Recent FW version provide new AT command: F0=2 which allows to solve the issue too mcuh AP
```
Comment (LMESTM) [inline ISM43362/ISM43362.cpp]: too mcuh AP => too many APs

File: ISM43362/ISM43362.cpp [hunk 2]
```diff
@@ -435,20 +438,54 @@ int ISM43362::scan(WiFiAccessPoint *res, unsigned limit)
...
+      With too much AP (depending on SSID name length), there is no answer from firmware to F0 command.
```
Comment (LMESTM) [inline ISM43362/ISM43362.cpp]: too many APs

File: ISM43362/ATParser/ATParser.cpp [hunk 3]
```diff
@@ -353,7 +353,7 @@ bool ATParser::vrecv(const char *response, va_list args)
 
             // Check for match
             int count = -1;
-            if (whole_line_wanted && c != '\n') {
+            if (whole_line_wanted && c != '\n' &&  c != '\r') {
```
Comment (LMESTM) [inline ISM43362/ATParser/ATParser.cpp]: add a comment in commit message about why this modification is needed.
i.e. Provide the exact format of response from WIFI module, ending with \r while all other commands are ending with \n

File: ISM43362/ISM43362.cpp [hunk 4]
```diff
@@ -435,20 +438,54 @@ int ISM43362::scan(WiFiAccessPoint *res, unsigned limit)
...
+
+
         if (res != 0 && limit != 0 && cnt >= limit) {
             /* reached end */
+            if (AP_Scan_1by1 == true) {
+                /* continue to receive AP 1 by 1 from firmware until we get OK */
+                while ((strncmp("OK\r", (char *)tmp, 2) != 0)) {
+                    _parser.flush();
+                    _parser.send("MR");
+                    _parser.recv("%[^\n^\r]\r\n", tmp);
```
Comment (LMESTM) [inline ISM43362/ISM43362.cpp]: Maybe check for errors or timeouts in the send and recv to make sure we never end up stuck into this loop in case the firmware reports an error ?

File: ISM43362/ISM43362.cpp (hunk 1 above)
Comment (ABOSTM) [reply ISM43362/ISM43362.cpp]: Done

File: ISM43362/ISM43362.cpp (hunk 2 above)
Comment (ABOSTM) [reply ISM43362/ISM43362.cpp]: Done

File: ISM43362/ATParser/ATParser.cpp (hunk 3 above)
Comment (ABOSTM) [reply ISM43362/ATParser/ATParser.cpp]: Done: inline comment

File: ISM43362/ISM43362.cpp (hunk 4 above)
Comment (ABOSTM) [reply ISM43362/ISM43362.cpp]: Done

File: ISM43362/ISM43362.cpp [hunk 5]
```diff
@@ -468,18 +468,35 @@ int ISM43362::scan(WiFiAccessPoint *res, unsigned limit)
...
+                    }
                 }
             }
             break;
         }
 
         if (AP_Scan_1by1 == true) {
-            /* In case of scan AP 1 by 1, end of list is detected thanks to OK */
+            /* In case of scan AP 1 by 1, end of list is detected thanks to OK or ERROR*/
+            if (strncmp("ERROR", (char *)tmp, 5) == 0) {
```
Comment (LMESTM) [inline ISM43362/ISM43362.cpp]: In case of ERROR you already returned 0 earlier so I am not sure if this check is needed
